image: python:3.10-buster

before_script:
  - pip install --upgrade pip
  - pip install -e .[dev]

stages:
  - test
  - deploy

pytest:
  stage: test
  script:
    - pytest -v --junitxml=test_log.xml --cov=expkit --cov-report xml
  artifacts:
    when: always
    paths:
      - test_log.xml
    reports:
      junit: test_log.xml
      coverage_report:
        coverage_format: cobertura
        file: coverage.xml

pages-test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pypi:
    stage: deploy
    script:
    - pip install --upgrade twine build
    - python -m build
    - twine check dist/*
    - twine upload dist/*
    - echo Deployed to PyPI
    artifacts:
      paths:
      - dist
    only:
      - tags
