image: python:3.10-buster

before_script:
  - pip --upgrade pip
  - pip install -e .[dev]

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pypi:
    stage: deploy
    script:
    - pip install --upgrade twine build
    - python -m build
    - twine check dist/*
    - cat $PYPIRC > .pypirc
    - true || twine upload dist/*
    - echo Deployed to PyPI
    after_script:
      - rm .pypirc
    only:
      - tags
    rules:
      - if: $CI_PIPELINE_SOURCE == "push"
      - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      - if: $CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?$/
